### ISSUE TITLE
Ошибка загрузки стран, городов, регионов. 

### ISSUE THREAD

**Issue by paurlift** [vgrish/gl#2]
Добрый день. 

Подскажите, пожалуйста, откуда загружать страны, города? 

Ошибка такого рода, при нажатии на значек загрузки появляется сообщение - "Вы уверены, что хотите выполнить загрузку? Текущие данные будут обновлены."  Я нажимаю - да. и дальше сообщение - "Файл не найден" -  http://joxi.ru/xAe0Od4hYM5B02

Спасибо.

**Comment by vgrish** [comment]
а вы отсюда скачали пакет?
тут нет файлов SxGeo оттого он и ругается.

Пакет можно установить с репозитория https://modstore.pro/ или с http://rstore.pro/extras/

**Comment by paurlift** [comment]
Да, пакет скачал отсюда. 

Спасибо, через репозиторий все установилось корректно.
