### ISSUE TITLE
После обновления до последней версии не может найти файлы

### ISSUE THREAD

**Issue by ViieeS** [vgrish/gl#3]
/assets/components/gl/vendor/select2/dist/js/select2.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/components/gl/vendor/select2/dist/css/select2.min.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by vgrish** [comment]
Попробуй переустановить пакет. Возможно сначала полностью деинсталлировать.

**Comment by ViieeS** [comment]
Спасибо, помогло. Как насчет добавить функционал? https://github.com/ViieeS/gl

**Comment by vgrish** [comment]
Пожалуйста.
А что это и зачем? Объясни подробнее.

**Comment by ViieeS** [comment]
По сути это поле для множественного выбора города, на основе твоего компонента, для отправки из фронта на сервер. В моем случае, оно интегрирована с NewsPublisher, что позволяет выбрать город и прикрепить к публикуемому ресурсу.

**Comment by vgrish** [comment]
а... да не. Не думаю что это необходимо, написать формочку для себя не составит особого труда, универсальности никакой тут нет, потому думаю это лишнее.
Спасибо.
