### ISSUE TITLE
Исключить из вывода города

### ISSUE THREAD

**Issue by BestFreelancer** [vgrish/gl#5]
Как в [[!gl.location]] Исключить из вывода нужные города? 

Для чего это нужно: у меня сначала идет Москва потом СПБ, сделал их вывод отдельными [[!gl.location]] и в условии написал город =  .....

Ставлю третий [[!gl.location]] для вывода всех остальных городов и вот в нем мне нужно исключить Москву и СПБ

**Comment by vgrish** [comment]
по вопросам есть прекрасное сообщество https://modx.pro/
задавайте их там пожалуйста!
